# Generated by Django 4.0.5 on 2022-07-11 18:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('symbol', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Fibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('website', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('form', models.IntegerField(choices=[(0, 'Ball'), (1, 'Roll'), (2, 'Precel')])),
                ('threads_number', models.IntegerField(null=True)),
                ('special_thread', models.CharField(blank=True, max_length=20, null=True)),
                ('length', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('manufacturer_symbol', models.CharField(max_length=50)),
                ('prepared', models.IntegerField(choices=[(1, 'Ready'), (2, 'Own Choice'), (3, 'On Demand'), (4, 'Limited')])),
                ('status', models.IntegerField(choices=[(0, 'Owned'), (1, 'Bought'), (3, 'Wanted')])),
                ('web_link', models.URLField(null=True)),
                ('colours', models.ManyToManyField(to='skeins.colour')),
                ('composition', models.ManyToManyField(to='skeins.component')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeins.manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='fibre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeins.fibre'),
        ),
        migrations.AddField(
            model_name='colour',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeins.manufacturer'),
        ),
        migrations.AlterUniqueTogether(
            name='colour',
            unique_together={('manufacturer', 'name')},
        ),
    ]
