# Generated by Django 4.0.5 on 2022-07-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeins', '0003_skein_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skein',
            name='manufacturer_symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
